"""Copies contract ABIs from the Foundry build output to the backend and the web app.

Run `forge build` in contracts/ first, or just `make abi`.
"""

import json
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
CONTRACTS = ["MockUSDC", "InvestorRegistry", "FundToken"]


def load_abi(name: str) -> list:
    artifact = ROOT / "contracts" / "out" / f"{name}.sol" / f"{name}.json"
    return json.loads(artifact.read_text())["abi"]


def to_ts(abis: dict[str, list]) -> str:
    lines = ["// Generated by scripts/export_abi.py, do not edit.", ""]
    for name, abi in abis.items():
        const = name[0].lower() + name[1:] + "Abi"
        lines.append(f"export const {const} = {json.dumps(abi, indent=2)} as const")
        lines.append("")
    return "\n".join(lines)


def main() -> None:
    abis = {name: load_abi(name) for name in CONTRACTS}
    (ROOT / "backend" / "app" / "abi.json").write_text(json.dumps(abis, indent=2) + "\n")
    (ROOT / "web" / "src" / "abi.ts").write_text(to_ts(abis))


if __name__ == "__main__":
    main()
